// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB49uWa6fUwrHDsZd7-ra3Y141-7ArmG8',
    appId: '1:58998087177:web:e8979c20b811d420d622d8',
    messagingSenderId: '58998087177',
    projectId: 'tech-store-fb741',
    authDomain: 'tech-store-fb741.firebaseapp.com',
    storageBucket: 'tech-store-fb741.firebasestorage.app',
    measurementId: 'G-YBELSWFSYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC8EgZ4A4zWr19ue4HXXiwAGlMDus-KqE',
    appId: '1:58998087177:android:48bfe23200f374e4d622d8',
    messagingSenderId: '58998087177',
    projectId: 'tech-store-fb741',
    storageBucket: 'tech-store-fb741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVE4Qm0ymk1mB5yK5OCMlFlk4bdNjNEfM',
    appId: '1:58998087177:ios:960dd6e967828fd7d622d8',
    messagingSenderId: '58998087177',
    projectId: 'tech-store-fb741',
    storageBucket: 'tech-store-fb741.firebasestorage.app',
    iosBundleId: 'com.example.techStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVE4Qm0ymk1mB5yK5OCMlFlk4bdNjNEfM',
    appId: '1:58998087177:ios:960dd6e967828fd7d622d8',
    messagingSenderId: '58998087177',
    projectId: 'tech-store-fb741',
    storageBucket: 'tech-store-fb741.firebasestorage.app',
    iosBundleId: 'com.example.techStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB49uWa6fUwrHDsZd7-ra3Y141-7ArmG8',
    appId: '1:58998087177:web:31d88ad54c8ffebbd622d8',
    messagingSenderId: '58998087177',
    projectId: 'tech-store-fb741',
    authDomain: 'tech-store-fb741.firebaseapp.com',
    storageBucket: 'tech-store-fb741.firebasestorage.app',
    measurementId: 'G-1FMVC5N9DL',
  );
}
